### ISSUE TITLE
[3장] p.99 application.yml 설정

### ISSUE THREAD

**Issue by nitronium102** [nitronium102/EFUB-SpringBoot-with-AWS#6]
MySQL5InnoDBDialect가 depreciated되었기 때문에 아래처럼 바꾸어 사용합니다.
```
spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
```
